if(NOT DEFINED SOURCE_DIR OR NOT DEFINED WORK_DIR OR NOT DEFINED PROFILE)
  message(FATAL_ERROR "profile test requires SOURCE_DIR, WORK_DIR, and PROFILE")
endif()
set(configure_arguments -S "${SOURCE_DIR}" -B "${WORK_DIR}"
  -DBUILD_TESTING=OFF -DFREI0R_BUILD_BUNDLE=ON
  "-DFREI0R_BUNDLE_PROFILE=${PROFILE}")
if(NOT NATIVE_DEPS)
  list(APPEND configure_arguments
    -DWITHOUT_OPENCV=ON -DWITHOUT_CAIRO=ON -DWITHOUT_GAVL=ON)
else()
  list(APPEND configure_arguments
    -DWITHOUT_OPENCV=OFF -DWITHOUT_CAIRO=OFF -DWITHOUT_GAVL=OFF)
endif()
if(DEFINED PLUGINS)
  string(REPLACE "," "\\;" plugins "${PLUGINS}")
  list(APPEND configure_arguments "-DFREI0R_BUNDLE_PLUGINS=${plugins}")
endif()
execute_process(
  COMMAND "${CMAKE_COMMAND}" ${configure_arguments}
  RESULT_VARIABLE configure_result
  OUTPUT_VARIABLE configure_output
  ERROR_VARIABLE configure_error)
if(NOT configure_result EQUAL 0)
  message(FATAL_ERROR "bundle profile configure failed: ${configure_output}\n${configure_error}")
endif()
file(STRINGS "${WORK_DIR}/CMakeCache.txt" resolved_line
  REGEX "^FREI0R_BUNDLE_RESOLVED_TARGETS:INTERNAL=")
if(NOT resolved_line)
  message(FATAL_ERROR "bundle profile did not record resolved targets")
endif()
string(REGEX REPLACE "^.*=" "" resolved_targets "${resolved_line}")
string(REPLACE "\\;" ";" resolved_targets "${resolved_targets}")
if(resolved_targets STREQUAL "")
  message(FATAL_ERROR "bundle profile resolved no targets")
endif()
file(STRINGS "${WORK_DIR}/CMakeCache.txt" classification_line
  REGEX "^FREI0R_BUNDLE_CLASSIFICATIONS:INTERNAL=")
if(NOT classification_line)
  message(FATAL_ERROR "bundle profile did not persist target classifications")
endif()
string(REGEX REPLACE "^.*=" "" classifications "${classification_line}")
string(REPLACE "\\;" ";" classifications "${classifications}")
list(LENGTH classifications classification_count)
if(DEFINED EXPECT_CLASSIFICATION_COUNT AND
   NOT classification_count EQUAL EXPECT_CLASSIFICATION_COUNT)
  message(FATAL_ERROR "classification count ${classification_count} differs from expected ${EXPECT_CLASSIFICATION_COUNT}")
endif()
if(DEFINED EXPECT_CLASSIFICATION_RECORDS)
  string(REPLACE "," ";" expected_classifications "${EXPECT_CLASSIFICATION_RECORDS}")
  foreach(expected IN LISTS expected_classifications)
    list(FIND classifications "${expected}" expected_index)
    if(expected_index EQUAL -1)
      message(FATAL_ERROR "missing final target classification '${expected}'")
    endif()
  endforeach()
endif()
if(DEFINED EXPECT_TARGETS)
  string(REPLACE "," ";" expected_targets "${EXPECT_TARGETS}")
  foreach(expected IN LISTS expected_targets)
    list(FIND resolved_targets "${expected}" expected_index)
    if(expected_index EQUAL -1)
      message(FATAL_ERROR "bundle profile omitted expected target '${expected}'")
    endif()
  endforeach()
endif()
if(DEFINED EXPECT_NOT_TARGETS)
  string(REPLACE "," ";" excluded_targets "${EXPECT_NOT_TARGETS}")
  foreach(excluded IN LISTS excluded_targets)
    list(FIND resolved_targets "${excluded}" excluded_index)
    if(NOT excluded_index EQUAL -1)
      message(FATAL_ERROR "bundle profile unexpectedly selected '${excluded}'")
    endif()
  endforeach()
endif()
foreach(target IN LISTS resolved_targets)
  string(REGEX REPLACE "[^A-Za-z0-9_]" "_" token "${target}")
  if(token MATCHES "^[0-9]" OR token STREQUAL "")
    set(token "plugin_${token}")
  endif()
  if(NOT EXISTS "${WORK_DIR}/bundle-descriptors/${token}-descriptor.c")
    message(FATAL_ERROR "resolved target '${target}' has no generated descriptor")
  endif()
  file(READ "${WORK_DIR}/bundle-descriptors/${token}-descriptor.c" descriptor)
  string(FIND "${descriptor}" "\"${target}\"" matching_id)
  if(matching_id EQUAL -1)
    message(FATAL_ERROR "descriptor for '${target}' does not retain its resolved ID")
  endif()
endforeach()
file(STRINGS "${WORK_DIR}/bundle-registry/frei0r-bundle-registry.c" registry_entries
  REGEX "^  &f0r_bundle_descriptor_")
list(LENGTH resolved_targets resolved_count)
list(LENGTH registry_entries registry_count)
if(NOT resolved_count EQUAL registry_count)
  message(FATAL_ERROR "registry count ${registry_count} differs from resolved target count ${resolved_count}")
endif()
